### ISSUE TITLE
How to use it in typescript?

### ISSUE THREAD

**Issue by BINAIMENG** [lvlrSajjad/sajjad-blur-overlay#7]
In typescript how to use it ? Please help
![image](https://user-images.githubusercontent.com/19889708/54911082-a0688000-4f28-11e9-88e0-8fc5209a219b.png)

**Comment by BINAIMENG** [comment]
@lvlrSajjad

**Comment by lvlrSajjad** [comment]
@BINAIMENG I must check that I will tell you. 
Can you tell me more about the problem with typescript?

**Comment by BINAIMENG** [comment]
I  have to use **settimeout** can work . typescript is fine
